name: 'Functional Test'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-defaults:
    name: Test Defaults (Repo, Ref)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo Locally
      uses: verily-src/actions-checkout@node-16
      with:
        path: actions-checkout
    - name: Checkout Repo
      uses: ./actions-checkout
      with:
        path: test-checkout
    - id: defaults
      working-directory: test-checkout
      run: |
        echo "sha=$(git show HEAD --pretty=format:%H --no-patch)" >> $GITHUB_OUTPUT
        echo "repo=$(git remote get-url origin | grep -oE [a-zA-Z0-9-]+/[a-zA-Z0-9-]+$)" >> $GITHUB_OUTPUT
    - name: Check Repo
      working-directory: test-checkout
      if: ${{ github.repository != steps.defaults.outputs.repo }}
      run: failure()
    - name: Check Ref
      working-directory: test-checkout
      if: ${{ github.sha != steps.defaults.outputs.sha }}
      run: failure()
